# -*- coding: utf-8 -*-
"""pdf extract data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QZz9NCcOZ1O3ip0SME2qVwQ_DlMy6mXV
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install llama-parse

!wget "https://ms.sapientia.ro/content/docs/MS/Felveteli/2025/MK_szenatusra_Felveteli_kriteriumok_2025_Mesteri.pdf" -O mesteri_kriterium.pdf

import nest_asyncio

nest_asyncio.apply()

import os

os.environ["LLAMA_CLOUD_API_KEY"] = "llx-icirJPG6EoKh0r0OpDWPczRxndH46Ovuly4XRul1wHJNaXhw"

from llama_parse import LlamaParse

document = LlamaParse(result_type="markdown").load_data("/content/mesteri_kriterium.pdf")

document

file_name = "mesteri_kriterium.md"
with open(file_name, 'w') as file:
    file.write(document[0].text)