# -*- coding: utf-8 -*-
"""Weboldal_informacio_leszedese_tisztitasa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IU_5NogghL_4kSrcnsNZa3xJmJcQLN47
"""

!pip install -q -U google-genai

!pip install requests beautifulsoup4 markdownify

import requests
from bs4 import BeautifulSoup
from markdownify import markdownify as md
from urllib.parse import urljoin, urlparse
import re
def url_to_markdown(url):
    try:
        # 1. Letölti az oldal tartalmát
        response = requests.get(url, timeout=10)
        response.raise_for_status()

        # 2. Kinyeri a HTML-tartalmat
        html = response.text
        soup = BeautifulSoup(html, 'html.parser')
        for i_tag in soup.find_all('i', class_='fa fa-at'):
          i_tag.replace_with('@')
        body = soup.body
        if body is None:
            raise ValueError("❌ Az oldal nem tartalmaz <body> elemet.")

        # 3. A domain gyökere (https://ms.sapientia.ro/)
        parsed = urlparse(response.url)
        base_root = f"{parsed.scheme}://{parsed.netloc}/"
        print(f"ℹ️ Domain gyökere: {base_root}")

        # 4. Keresés a <div id="nright"> és pageheader elemekben

        targets = [
          soup.find('div', {'id': 'nright'}),
          soup.find('div', {'id': 'pageheader'}),
        ]

        for container in targets:
            if container:
                # 5. Az összes relatív <a> és <img> link teljes URL-re hozása ezen a konténeren belül
                for tag in container.find_all(['a', 'img']):
                    attr = 'href' if tag.name == 'a' else 'src'
                    if tag.has_attr(attr):
                        val = tag[attr]
                        ## Ha nem http/https link, akkor kiegészítjük teljes URL-re
                        if not val.startswith(('http://', 'https://')):
                            tag[attr] = urljoin(base_root, val)
                        # Az URL-t szóköz hozzáfűzésével mentjük el
                        tag[attr] = f"{tag[attr]} "



        # 6. A teljes HTML átalakítása Markdown formátumba
        markdown = md(str(body), heading_style="ATX")

        return markdown

    except Exception as error:
        print(f"⚠️ Hiba történt az URL feldolgozása során: {url}")
        print(f"Részletek: {error}")
        return ""

#url = "https://ms.sapientia.ro/hu/a-karrol/rolunk/kuldetes"
#url = "https://ms.sapientia.ro/hu/a-karrol/rolunk/magunkrol"
#url = "https://ms.sapientia.ro/hu/a-karrol/rolunk/munkatarsak"
#url = "https://ms.sapientia.ro/hu/a-karrol/rolunk/munkatarsak/dekani-hivatal_"
#url = "https://ms.sapientia.ro/hu/a-karrol/rolunk/munkatarsak/gazdasagi-osztaly_"
#url = ""https://ms.sapientia.ro/hu/a-karrol/rolunk/munkatarsak/adminisztracio_"
#url = "https://ms.sapientia.ro/hu/a-karrol/rolunk/munkatarsak/konyvtar__"
#url = "https://ms.sapientia.ro/hu/a-karrol/rolunk/szervezeti-abra"
#url = "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/kari-vezetok"
#url = "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/kari-tanacs"
#url = "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok"
#url = "https://ms.sapientia.ro/hu/a-karrol/tanszeke"
#url = "https://ms.sapientia.ro/hu/a-karrol/konyvtar"
#url = "https://ms.sapientia.ro/hu/a-karrol/hallgatoi-onkormanyzat"
#url = "https://sapientia.ro/hu/az-egyetemrol/akkreditacio"
#url = "https://ms.sapientia.ro/hu/a-karrol/alumni"
#url = "https://ms.sapientia.ro/hu/a-karrol/elerhetosegek"
#url = "https://ms.sapientia.ro/hu/oktatas/tanevszerkezet"
#url = "https://ms.sapientia.ro/hu/oktatas/orarend"
#url = "https://ms.sapientia.ro/hu/oktatas/tantargyi-adatlapok"
#url = "https://ms.sapientia.ro/hu/oktatas/tantervek"
#url = "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-tajekoztato"
#url = "https://ms.sapientia.ro/hu/hallgatoknak/vizsgaidopontok"
#url = "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/adminisztrativ-dijak_"
url = "https://ms.sapientia.ro/hu/hallgatoknak/kari-tdk"
markdown_szoveg = url_to_markdown(url)

print(markdown_szoveg)  # Itt láthatod a Markdown-tartalmat

konyvtar = "könyvtár"
akkrecitacio = "Akkreditáció"
idei_ev = "Csak 2025-ös tanévet tarsd meg."
tantargyi_adatlapk_linkjei = "Tantárgyi adatlapok"
tantervek = "Tantervek"
Adminisztrativ_dijak = "Adminisztratív díjak"
kariTdk="Kari TDK"

szovegek_pipline = f"""
      Feladat:
          Tisztítsd meg az alábbi markdown szöveget.
          A fő tartalmat {kariTdk} és {idei_ev} tartsd meg.

          Törlendő részek:
          - navigációs menük
          - oldalsó navigációs menük linkjei
          - lábléc
          - jogi információk
          - ismétlődő címek
          - hírek
          - képek linkjei
          - ismétlődő nevek"""

szoveg_link_pipline = f"""
      Feladat:
          Tisztítsd meg az alábbi markdown szöveget.
          A fő tartalmat {tantervek} tartsd meg.
          A linkek add ilyen formátumban: téma (http://link).

          Törlendő részek:
          - navigációs menük
          - menük linkjei
          - Lábléc
          - kapcsolodó linkek
          - jogi információk
          - ismétlődő címek
          - hirek
          - képek linkjei
          - ismétlődő nevek"""

from google import genai
client = genai.Client(api_key="AIzaSyCLIFWdK7JZX8LnP8liIJ3UMop4Gfa6qPQ")

response = client.models.generate_content(
    model="gemini-2.0-flash-thinking-exp-01-21",
    contents = [f"""
          {szovegek_pipline}
          Szöveg:
          {markdown_szoveg}
          """]

)
print(response.text)

#file_path = '/content/markdown_konyvtar.md'
#file_path = '/content/markdown_oktatas.md'
#file_path = '/content/markdown_output.md'
file_path = '/content/markdown_hallgatoknak.md'


with open(file_path, 'a') as f:
  f.write(response.text)

# Fájl elérési útja
file_path

list_urls = [
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/informatika-bizottsag-",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/minosegbiztositasi-bizottsag-",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/akkreditacios-bizottsag",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/tanulmanyi-es-kredit-bizottsag-",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/kari-osztondij-tanacs",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/kari-erasmus-bizottsag",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/erasmus-szocialis-osztondij-bizottsag",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/tudomanyos-kutatas-bizottsaga",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/kari-beszerzesi-elbiralo-bizottsag-",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/kari-tudomanyos-diakkori-tanacs",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/orarendkeszito-bizottsag",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/kari-valasztasi-bizottsag",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/kari-hallgatoi-valasztasi-bizottsag"
           ]

tanszek_pipline = """ Feladat:
          Tisztítsd meg az alábbi markdown szöveget. A fő tartalmat (tanszéken lévő információkat, dolgozókat és szerepkörük) tartsd meg.
          A linkeket formátumban add vissza: téma (https://link)

          Törlendő részek:
          - navigációs menük
          - oldalsó navigációs menük linkjei
          - Lábléc
          - kapcsolodó linkek
          - jogi információk
          - ismétlődő címek
          - Hírek
          - képek linkjei
          - ismétlődő nevek  """

from google import genai

def web_scraping_clean(list_urls):
  for item_url in list_urls:
    markdown_szoveg = url_to_markdown(item_url)
    if markdown_szoveg:
      client = genai.Client(api_key="AIzaSyCLIFWdK7JZX8LnP8liIJ3UMop4Gfa6qPQ")
      response = client.models.generate_content(
          model="gemini-2.0-flash-thinking-exp-01-21",
          contents = [f"""
          {szovegek_pipline}
          Szöveg:
          {markdown_szoveg}
          """]
          #contents=[f"Tisztítsd meg a markdown formátumú szöveget: {markdown_szoveg}. Tartsd meg a fő tartalmat, eltávolítva minden nem informatív rész, mint navigációs menü és menü linkjei, lábléce, jogi információ, és ismétlődő szöveg. A dokumentumlinkek a következő formátumban: téma (https://link)."]
      )
      # response objektumnak van-e text attribútuma
      if response and  hasattr(response, 'text'):
          print(response.text)
          #file_path = '/content/markdown_karieriroda.md'
          file_path = '/content/markdown_konyvtar.md'

          with open(file_path, 'a') as f:
            f.write(response.text)
      else:
          print(f"Hiba történt a válasz feldolgozása során: {response}")

web_scraping_clean(list_urls)

tanszek_urls= ["https://ms.sapientia.ro/hu/a-karrol/tanszeke/alkalmazott-nyelveszeti-tanszek",
               "https://ms.sapientia.ro/hu/a-karrol/tanszeke/alkalmazott-tarsadalomtudomanyok-tanszek",
               "https://ms.sapientia.ro/hu/a-karrol/tanszeke/gepeszmernoki-tanszek",
               "https://ms.sapientia.ro/hu/a-karrol/tanszeke/kerteszmernoki-tanszek",
               "https://ms.sapientia.ro/hu/a-karrol/tanszeke/matematika-informatika-tanszek",
               "https://ms.sapientia.ro/hu/a-karrol/tanszeke/villamosmernoki-tanszek"]

web_scraping_clean(tanszek_urls)

karieriroda_urls=[ "https://ms.sapientia.ro/hu/a-karrol/karrieriroda/kuldetes_",
                   "https://ms.sapientia.ro/hu/a-karrol/karrieriroda/tevekenysegek",
                   "https://ms.sapientia.ro/hu/a-karrol/karrieriroda/esemenyek/marosvasarhelyi-karrierborze-2025",
                   ]

allasajanlatok_urls= ["https://ms.sapientia.ro/hu/a-karrol/karrieriroda/allasajanlatok-es-szakmai-gyakorlat",
                      "https://ms.sapientia.ro/hu/a-karrol/karrieriroda/allasajanlatok-es-szakmai-gyakorlat/allasajanlatok",
                      "https://ms.sapientia.ro/hu/a-karrol/karrieriroda/allasajanlatok-es-szakmai-gyakorlat/internship-ajanlatok",
                      "https://ms.sapientia.ro/hu/a-karrol/karrieriroda/allasajanlatok-es-szakmai-gyakorlat/szakmai-gyakorlat-lehetosegek"]

web_scraping_clean(karieriroda_urls)

web_scraping_clean(allasajanlatok_urls)

konyvtar_urls = [ "https://ms.sapientia.ro/hu/a-karrol/konyvtar/a-konyvtarrol",
                 "https://ms.sapientia.ro/hu/a-karrol/konyvtar/szolgaltatasok",
                  "https://ms.sapientia.ro/hu/a-karrol/konyvtar/beiratkozas",
                  "https://ms.sapientia.ro/hu/a-karrol/konyvtar/katalogus"]

web_scraping_clean(konyvtar_urls)

#egy másik .md fájl tartalmát hozzáfűzi a target_file(cél) .md fájl végéhez.

def append_md_file(target_file: str, source_file: str):
    """
    :param target_file: Az a fájl, amelyhez hozzá szeretnénk fűzni.
    :param source_file: Az a fájl, amelynek tartalmát hozzáfűzzük.
    """
    try:
        with open(source_file, 'r', encoding='utf-8') as f:
            content = f.read()

        with open(target_file, 'a', encoding='utf-8') as f:
            f.write("\n\n")  # optional separator
            f.write(content)

        print(f"Sikeresen hozzáfűztük a(z) '{source_file}' tartalmát a '{target_file}' fájlhoz.")

    except FileNotFoundError as e:
        print(f"Hiba: Nem található a fájl - {e}")
    except Exception as e:
        print(f"Hiba történt: {e}")

append_md_file('markdown_output.md','markdown_bizottsagok.md')

append_md_file('markdown_output.md','markdown_tanszekek.md')

append_md_file('markdown_output.md','markdown_karieriroda.md')

append_md_file('markdown_output.md','markdown_konyvtar.md')

hallgatok_urls = ["https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-tajekoztato",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-tajekoztato/altalanos-informaciok-az-egyetemrol",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-tajekoztato/gyakorlati-orak-potlasa",
                  "https://ms.sapientia.ro/hu/hallgatoknak/szakkoordinatorok",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/osztondijak",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/osztondijak/osztondijakrol-altalaban",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/osztondijak/alkalmi-osztondijak",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/osztondijak/erdemosztondij",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/osztondijak/tanulmanyi-osztondij",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/osztondijak/szocialis-osztondij",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/osztondijak/ferber-osztondij",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/fizetesi-hataridok",
                  "https://sapientia.ro/hu/oktatas/hallgatoknak/neptun",
                  "https://ms.sapientia.ro/hu/a-karrol/dokumentumok_",
                  "https://sapientia.ro/hu/oktatas/hallgatoknak/oklevelek-atvete",
                  "https://ms.sapientia.ro/hu/hallgatoknak/orvosi-rendelo",
                  "https://ms.sapientia.ro/hu/hallgatoknak/lelkigondozas"

                  ]

from google import genai

def web_scraping_markdown_to_clean(hallgatok_urls):
  for item_url in hallgatok_urls:
    markdown_szoveg = url_to_markdown(item_url)
    if markdown_szoveg:
      item_url_name = item_url.split('/')[-1]
      print(item_url_name)
      client = genai.Client(api_key="AIzaSyCLIFWdK7JZX8LnP8liIJ3UMop4Gfa6qPQ")
      response = client.models.generate_content(
          model="gemini-2.0-flash-thinking-exp-01-21",
          contents = [f"""
      Feladat:
          Tisztítsd meg az alábbi markdown szöveget.
          A fő tartalmat {item_url_name} tartsd meg.
          Csak a fő tartalomban {item_url_name}-ban lévő linkeket add ilyen formátumban: téma (http://link).
          Ha nincsenek linkek {item_url_name}-ban akkor csak a szöveget add vissza fő tartalomnak.

          Törlendő részek:
          - navigációs menük
          - menük linkjei
          - lábléc
          - kapcsolodó linkek
          - jogi információk
          - ismétlődő címek
          - hírek
          - képek linkjei
          - ismétlődő nevek

          Szöveg:
          {markdown_szoveg}
          """]
      )
      # response objektumnak van-e text attribútuma
      if response and  hasattr(response, 'text'):
          print(response.text)
          #file_path = '/content/markdown_hallgatoknak.md'
          file_path = '/content/markdown_zarovizsga.md'

          with open(file_path, 'a') as f:
            f.write(response.text)

      else:
          print(f"Hiba történt a válasz feldolgozása során: {response}")

web_scraping_markdown_to_clean(hallgatok_urls)

zarovizsga_urls = [ "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/automatika-es-alkalmazott-informatika",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/fordito-es-tolmacs",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/gepeszmernoki",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/infokommunikacios-halozatok-es-rendszerek-tavkozles",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/informatika",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/kerteszmernoki",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/kommunikacio-es-kozkapcsolatok",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/kozegeszsegugyi-szolgaltatasok-es-politikak-",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/mechatronika",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/szamitastechnika",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/tajepiteszet",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/tanarkepzo-intezet-20202021",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/mesterkepzes-utemezes-20242025",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/mesterkepzes-utemezes-20242025/szoftverfejlesztes",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/nyelvvizsga_",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/nyelvvizsga-20242025",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/alkalmazott-nyelveszeti-tanszek__/fordito-es-tolmacs-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/alkalmazott-tarsadalomtudomanyi-tanszek_/kommunikacio-es-kozkapcsolatok-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/alkalmazott-tarsadalomtudomanyi-tanszek_/kozegeszsegugyi-szolgaltatasok-es-politikak-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/gepeszmernoki-tanszek__/gepeszmernoki-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/gepeszmernoki-tanszek__/mechatronika-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/kerteszmernoki-tanszek__/kerteszmernoki-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/kerteszmernoki-tanszek__/tajepiteszet-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/kerteszmernoki-tanszek__/novenyorvos-mesteri-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/matematika-informatika-tanszek__/informatika-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/matematika-informatika-tanszek__/szoftverfejlesztes-mesterszak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/villamosmernoki-tanszek__/automatika-es-alkalmazott-informatika-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/villamosmernoki-tanszek__/infokommunikacios-halozatok-es-rendszerek-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/villamosmernoki-tanszek__/szamitastechnika-szak",
                    "https://sapientia.ro/hu/oktatas/tanarkepzes/a-zarovizsga-metodologiaja",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/szabalyzatok-es-iratok"
                  ]

web_scraping_markdown_to_clean(zarovizsga_urls)

