# -*- coding: utf-8 -*-
"""Weboldal_informacio_leszedese_tisztitasa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IU_5NogghL_4kSrcnsNZa3xJmJcQLN47
"""

!pip install -q -U google-genai

!pip install requests beautifulsoup4 markdownify

import requests
from bs4 import BeautifulSoup
from markdownify import markdownify as md
from urllib.parse import urljoin, urlparse
import re
def url_to_markdown(url):
    try:
        # 1. Letölti az oldal tartalmát
        response = requests.get(url, timeout=10)
        response.raise_for_status()

        # 2. Kinyeri a HTML-tartalmat
        html = response.text
        soup = BeautifulSoup(html, 'html.parser')
        for i_tag in soup.find_all('i', class_='fa fa-at'):
          i_tag.replace_with('@')
        body = soup.body
        if body is None:
            raise ValueError("❌ Az oldal nem tartalmaz <body> elemet.")

        # 3. A domain gyökere (https://ms.sapientia.ro/)
        parsed = urlparse(response.url)
        base_root = f"{parsed.scheme}://{parsed.netloc}/"
        print(f"ℹ️ Domain gyökere: {base_root}")

        # 4. Keresés a <div id="nright"> és pageheader elemekben

        targets = [
          soup.find('div', {'id': 'nright'}),
          soup.find('div', {'id': 'pageheader'}),
        ]

        for container in targets:
            if container:
                # 5. Az összes relatív <a> és <img> link teljes URL-re hozása ezen a konténeren belül
                for tag in container.find_all(['a', 'img']):
                    attr = 'href' if tag.name == 'a' else 'src'
                    if tag.has_attr(attr):
                        val = tag[attr]
                        ## Ha nem http/https link, akkor kiegészítjük teljes URL-re
                        if not val.startswith(('http://', 'https://')):
                            tag[attr] = urljoin(base_root, val)
                        # Az URL-t szóköz hozzáfűzésével mentjük el
                        tag[attr] = f"{tag[attr]} "



        # 6. A teljes HTML átalakítása Markdown formátumba
        markdown = md(str(body), heading_style="ATX")

        return markdown

    except Exception as error:
        print(f"⚠️ Hiba történt az URL feldolgozása során: {url}")
        print(f"Részletek: {error}")
        return ""

#url = "https://ms.sapientia.ro/hu/a-karrol/rolunk/kuldetes"
#url = "https://ms.sapientia.ro/hu/a-karrol/rolunk/magunkrol"
#url = "https://ms.sapientia.ro/hu/a-karrol/rolunk/munkatarsak"
#url = "https://ms.sapientia.ro/hu/a-karrol/rolunk/munkatarsak/dekani-hivatal_"
#url = "https://ms.sapientia.ro/hu/a-karrol/rolunk/munkatarsak/gazdasagi-osztaly_"
#url = ""https://ms.sapientia.ro/hu/a-karrol/rolunk/munkatarsak/adminisztracio_"
#url = "https://ms.sapientia.ro/hu/a-karrol/rolunk/munkatarsak/konyvtar__"
#url = "https://ms.sapientia.ro/hu/a-karrol/rolunk/szervezeti-abra"
#url = "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/kari-vezetok"
#url = "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/kari-tanacs"
#url = "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok"
#url = "https://ms.sapientia.ro/hu/a-karrol/tanszeke"
#url = "https://ms.sapientia.ro/hu/a-karrol/konyvtar"
#url = "https://ms.sapientia.ro/hu/a-karrol/hallgatoi-onkormanyzat"
#url = "https://sapientia.ro/hu/az-egyetemrol/akkreditacio"
#url = "https://ms.sapientia.ro/hu/a-karrol/alumni"
#url = "https://ms.sapientia.ro/hu/a-karrol/elerhetosegek"
#url = "https://ms.sapientia.ro/hu/oktatas/tanevszerkezet"
#url = "https://ms.sapientia.ro/hu/oktatas/orarend"
#url = "https://ms.sapientia.ro/hu/oktatas/tantargyi-adatlapok"
#url = "https://ms.sapientia.ro/hu/oktatas/tantervek"
#url = "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-tajekoztato"
#url = "https://ms.sapientia.ro/hu/hallgatoknak/vizsgaidopontok"
#url = "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/adminisztrativ-dijak_"
#url = "https://ms.sapientia.ro/hu/hallgatoknak/kari-tdk"
url = "https://ms.sapientia.ro/hu/felveteli"
markdown_szoveg = url_to_markdown(url)

print(markdown_szoveg)  # Itt láthatod a Markdown-tartalmat

konyvtar = "könyvtár"
akkrecitacio = "Akkreditáció"
idei_ev = "Csak 2025-ös tanévet tarsd meg."
tantargyi_adatlapk_linkjei = "Tantárgyi adatlapok"
tantervek = "Tantervek"
Adminisztrativ_dijak = "Adminisztratív díjak"
kariTdk="Kari TDK"
felveteli = "Felvételi oldal linkei"

szovegek_pipline = f"""
      Feladat:
          Tisztítsd meg az alábbi markdown szöveget.
          A fő tartalmat {kariTdk} és {idei_ev} tartsd meg.

          Törlendő részek:
          - navigációs menük
          - oldalsó navigációs menük linkjei
          - lábléc
          - jogi információk
          - ismétlődő címek
          - hírek
          - képek linkjei
          - ismétlődő nevek"""

szoveg_link_pipline = f"""
      Feladat:
          Tisztítsd meg az alábbi markdown szöveget.
          A fő tartalmat ({felveteli}) tartsd meg.
          A linkek add ilyen formátumban: téma (http://link).

          Törlendő részek:
          - navigációs menük
          - menük linkjei
          - Lábléc
          - kapcsolodó linkek
          - jogi információk
          - ismétlődő címek
          - hirek
          - képek linkjei
          - ismétlődő nevek"""

from google import genai
client = genai.Client(api_key="AIzaSyCLIFWdK7JZX8LnP8liIJ3UMop4Gfa6qPQ")

response = client.models.generate_content(
    model="gemini-2.0-flash-thinking-exp-01-21",
    contents = [f"""
          {szoveg_link_pipline}
          Szöveg:
          {markdown_szoveg}
          """]

)
print(response.text)

#file_path = '/content/markdown_konyvtar.md'
#file_path = '/content/markdown_oktatas.md'
#file_path = '/content/markdown_output.md'
#file_path = '/content/markdown_hallgatoknak.md'
file_path = '/content/markdown_felveteli.md'



with open(file_path, 'a') as f:
  f.write(response.text)

# Fájl elérési útja
file_path

list_urls = [
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/informatika-bizottsag-",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/minosegbiztositasi-bizottsag-",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/akkreditacios-bizottsag",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/tanulmanyi-es-kredit-bizottsag-",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/kari-osztondij-tanacs",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/kari-erasmus-bizottsag",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/erasmus-szocialis-osztondij-bizottsag",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/tudomanyos-kutatas-bizottsaga",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/kari-beszerzesi-elbiralo-bizottsag-",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/kari-tudomanyos-diakkori-tanacs",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/orarendkeszito-bizottsag",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/kari-valasztasi-bizottsag",
             "https://ms.sapientia.ro/hu/a-karrol/a-kar-vezetese/bizottsagok/kari-hallgatoi-valasztasi-bizottsag"
           ]

tanszek_pipline = """ Feladat:
          Tisztítsd meg az alábbi markdown szöveget. A fő tartalmat (tanszéken lévő információkat, dolgozókat és szerepkörük) tartsd meg.
          A linkeket formátumban add vissza: téma (https://link)

          Törlendő részek:
          - navigációs menük
          - oldalsó navigációs menük linkjei
          - Lábléc
          - kapcsolodó linkek
          - jogi információk
          - ismétlődő címek
          - Hírek
          - képek linkjei
          - ismétlődő nevek  """

from google import genai

def web_scraping_clean(list_urls):
  for item_url in list_urls:
    markdown_szoveg = url_to_markdown(item_url)
    if markdown_szoveg:
      client = genai.Client(api_key="AIzaSyCLIFWdK7JZX8LnP8liIJ3UMop4Gfa6qPQ")
      response = client.models.generate_content(
          model="gemini-2.0-flash-thinking-exp-01-21",
          contents = [f"""
          {szovegek_pipline}
          Szöveg:
          {markdown_szoveg}
          """]
          #contents=[f"Tisztítsd meg a markdown formátumú szöveget: {markdown_szoveg}. Tartsd meg a fő tartalmat, eltávolítva minden nem informatív rész, mint navigációs menü és menü linkjei, lábléce, jogi információ, és ismétlődő szöveg. A dokumentumlinkek a következő formátumban: téma (https://link)."]
      )
      # response objektumnak van-e text attribútuma
      if response and  hasattr(response, 'text'):
          print(response.text)
          #file_path = '/content/markdown_karieriroda.md'
          file_path = '/content/markdown_konyvtar.md'

          with open(file_path, 'a') as f:
            f.write(response.text)
      else:
          print(f"Hiba történt a válasz feldolgozása során: {response}")

web_scraping_clean(list_urls)

tanszek_urls= ["https://ms.sapientia.ro/hu/a-karrol/tanszeke/alkalmazott-nyelveszeti-tanszek",
               "https://ms.sapientia.ro/hu/a-karrol/tanszeke/alkalmazott-tarsadalomtudomanyok-tanszek",
               "https://ms.sapientia.ro/hu/a-karrol/tanszeke/gepeszmernoki-tanszek",
               "https://ms.sapientia.ro/hu/a-karrol/tanszeke/kerteszmernoki-tanszek",
               "https://ms.sapientia.ro/hu/a-karrol/tanszeke/matematika-informatika-tanszek",
               "https://ms.sapientia.ro/hu/a-karrol/tanszeke/villamosmernoki-tanszek"]

web_scraping_clean(tanszek_urls)

karieriroda_urls=[ "https://ms.sapientia.ro/hu/a-karrol/karrieriroda/kuldetes_",
                   "https://ms.sapientia.ro/hu/a-karrol/karrieriroda/tevekenysegek",
                   "https://ms.sapientia.ro/hu/a-karrol/karrieriroda/esemenyek/marosvasarhelyi-karrierborze-2025",
                   ]

allasajanlatok_urls= ["https://ms.sapientia.ro/hu/a-karrol/karrieriroda/allasajanlatok-es-szakmai-gyakorlat",
                      "https://ms.sapientia.ro/hu/a-karrol/karrieriroda/allasajanlatok-es-szakmai-gyakorlat/allasajanlatok",
                      "https://ms.sapientia.ro/hu/a-karrol/karrieriroda/allasajanlatok-es-szakmai-gyakorlat/internship-ajanlatok",
                      "https://ms.sapientia.ro/hu/a-karrol/karrieriroda/allasajanlatok-es-szakmai-gyakorlat/szakmai-gyakorlat-lehetosegek"]

web_scraping_clean(karieriroda_urls)

web_scraping_clean(allasajanlatok_urls)

konyvtar_urls = [ "https://ms.sapientia.ro/hu/a-karrol/konyvtar/a-konyvtarrol",
                 "https://ms.sapientia.ro/hu/a-karrol/konyvtar/szolgaltatasok",
                  "https://ms.sapientia.ro/hu/a-karrol/konyvtar/beiratkozas",
                  "https://ms.sapientia.ro/hu/a-karrol/konyvtar/katalogus"]

web_scraping_clean(konyvtar_urls)

#egy másik .md fájl tartalmát hozzáfűzi a target_file(cél) .md fájl végéhez.

def append_md_file(target_file: str, source_file: str):
    """
    :param target_file: Az a fájl, amelyhez hozzá szeretnénk fűzni.
    :param source_file: Az a fájl, amelynek tartalmát hozzáfűzzük.
    """
    try:
        with open(source_file, 'r', encoding='utf-8') as f:
            content = f.read()

        with open(target_file, 'a', encoding='utf-8') as f:
            f.write("\n\n")  # optional separator
            f.write(content)

        print(f"Sikeresen hozzáfűztük a(z) '{source_file}' tartalmát a '{target_file}' fájlhoz.")

    except FileNotFoundError as e:
        print(f"Hiba: Nem található a fájl - {e}")
    except Exception as e:
        print(f"Hiba történt: {e}")

append_md_file('markdown_output.md','markdown_bizottsagok.md')

append_md_file('markdown_output.md','markdown_tanszekek.md')

append_md_file('markdown_output.md','markdown_karieriroda.md')

append_md_file('markdown_output.md','markdown_konyvtar.md')

hallgatok_urls = ["https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-tajekoztato",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-tajekoztato/altalanos-informaciok-az-egyetemrol",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-tajekoztato/gyakorlati-orak-potlasa",
                  "https://ms.sapientia.ro/hu/hallgatoknak/szakkoordinatorok",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/osztondijak",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/osztondijak/osztondijakrol-altalaban",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/osztondijak/alkalmi-osztondijak",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/osztondijak/erdemosztondij",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/osztondijak/tanulmanyi-osztondij",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/osztondijak/szocialis-osztondij",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/osztondijak/ferber-osztondij",
                  "https://ms.sapientia.ro/hu/hallgatoknak/hallgatoi-penzugyek/fizetesi-hataridok",
                  "https://sapientia.ro/hu/oktatas/hallgatoknak/neptun",
                  "https://ms.sapientia.ro/hu/a-karrol/dokumentumok_",
                  "https://sapientia.ro/hu/oktatas/hallgatoknak/oklevelek-atvete",
                  "https://ms.sapientia.ro/hu/hallgatoknak/orvosi-rendelo",
                  "https://ms.sapientia.ro/hu/hallgatoknak/lelkigondozas"

                  ]

from google import genai

def web_scraping_markdown_to_clean(hallgatok_urls):
  for item_url in hallgatok_urls:
    markdown_szoveg = url_to_markdown(item_url)
    if markdown_szoveg:
      item_url_name = item_url.split('/')[-1]
      print(item_url_name)
      client = genai.Client(api_key="AIzaSyCLIFWdK7JZX8LnP8liIJ3UMop4Gfa6qPQ")
      response = client.models.generate_content(
          model="gemini-2.0-flash-thinking-exp-01-21",
          contents = [f"""
      Feladat:
          Tisztítsd meg az alábbi markdown szöveget.
          A fő tartalmat ({item_url_name}) tartsd meg.
          Csak a fő tartalomban ({item_url_name}-ban) lévő linkeket add ilyen formátumban: téma (http://link).
          Ha a {item_url_name}-ban nincsenek dokumentumlinkek csak a szöveget tarsd meg.

          Távolítsd el a következőket:
          - navigációs menük és linkjeik
          - lábléc
          - kapcsolodó linkek
          - jogi információk
          - ismétlődő cím
          - hírek
          - képek linkjei
          - ismétlődő név
          - ismétlődő dokumentumlink


          Szöveg:
          {markdown_szoveg}
          """]
      )
      # response objektumnak van-e text attribútuma
      if response and  hasattr(response, 'text'):
          print(response.text)
          #file_path = '/content/markdown_hallgatoknak.md'
          #file_path = '/content/markdown_zarovizsga.md'
          #file_path = '/content/markdown_bentlakas.md'
          #file_path = '/content/markdown_tanarkepzes.md'
          #file_path = '/content/markdown_kutatas.md'
          file_path = '/content/markdown_nemzetkozi_kapcsolatok.md'

          with open(file_path, 'a') as f:
            f.write(response.text)

      else:
          print(f"Hiba történt a válasz feldolgozása során: {response}")

web_scraping_markdown_to_clean(hallgatok_urls)

zarovizsga_urls = [ "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/automatika-es-alkalmazott-informatika",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/fordito-es-tolmacs",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/gepeszmernoki",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/infokommunikacios-halozatok-es-rendszerek-tavkozles",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/informatika",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/kerteszmernoki",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/kommunikacio-es-kozkapcsolatok",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/kozegeszsegugyi-szolgaltatasok-es-politikak-",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/mechatronika",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/szamitastechnika",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/tajepiteszet",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/alapkepzes-utemezes-es-tematikak-20242025/tanarkepzo-intezet-20202021",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/mesterkepzes-utemezes-20242025",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/mesterkepzes-utemezes-20242025/szoftverfejlesztes",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/nyelvvizsga_",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/nyelvvizsga-20242025",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/alkalmazott-nyelveszeti-tanszek__/fordito-es-tolmacs-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/alkalmazott-tarsadalomtudomanyi-tanszek_/kommunikacio-es-kozkapcsolatok-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/alkalmazott-tarsadalomtudomanyi-tanszek_/kozegeszsegugyi-szolgaltatasok-es-politikak-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/gepeszmernoki-tanszek__/gepeszmernoki-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/gepeszmernoki-tanszek__/mechatronika-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/kerteszmernoki-tanszek__/kerteszmernoki-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/kerteszmernoki-tanszek__/tajepiteszet-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/kerteszmernoki-tanszek__/novenyorvos-mesteri-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/matematika-informatika-tanszek__/informatika-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/matematika-informatika-tanszek__/szoftverfejlesztes-mesterszak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/villamosmernoki-tanszek__/automatika-es-alkalmazott-informatika-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/villamosmernoki-tanszek__/infokommunikacios-halozatok-es-rendszerek-szak",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/zarovizsga-keszitesi-utmutatok/villamosmernoki-tanszek__/szamitastechnika-szak",
                    "https://sapientia.ro/hu/oktatas/tanarkepzes/a-zarovizsga-metodologiaja",
                    "https://ms.sapientia.ro/hu/hallgatoknak/zarovizsga/szabalyzatok-es-iratok"
                  ]

web_scraping_markdown_to_clean(zarovizsga_urls)

felveteli_tudnivalok_urls = [ "https://ms.sapientia.ro/hu/felveteli"
                              "https://ms.sapientia.ro/hu/felveteli/felveteli-tudnivalok_/felveteli-kriteriumok-es-beiskolazasi-szamok-2025",
                              "https://ms.sapientia.ro/hu/felveteli/felveteli-tudnivalok_/felveteli-mappahoz-szukseges-iratok",
                              "https://ms.sapientia.ro/hu/felveteli/felveteli-tudnivalok_/felveteli-tematika",
                              "https://ms.sapientia.ro/hu/felveteli/felveteli-tudnivalok_/felveteli-szabalyzatok",
                              "https://ms.sapientia.ro/hu/felveteli/felveteli-tudnivalok_/lapozhato-tajekoztato-fuzet",
                              "https://ms.sapientia.ro/hu/felveteli/felveteli-tudnivalok_/kulfoldi-oklevellel-rendelkezok-beiratkozasa",

                  ]

web_scraping_markdown_to_clean(felveteli_tudnivalok_urls)

bentlakas_urls= [ "https://ms.sapientia.ro/hu/hallgatoknak/bentlakas_",
                 "https://ms.sapientia.ro/hu/hallgatoknak/bentlakas_/bentlakas-jelentkezesi-kriteriumok-es-szukseges-iratok-2024-2025-evre-elso-evesek",
                  "https://ms.sapientia.ro/hu/hallgatoknak/bentlakas_/szabalyzat_",
                  "https://ms.sapientia.ro/hu/hallgatoknak/bentlakas_/araink_",
                  "https://ms.sapientia.ro/hu/hallgatoknak/bentlakas_/bentlakassal-kapcsolatos-koltsegek-kifizetese_"]

web_scraping_markdown_to_clean(bentlakas_urls)

tanarkepzes_urls=[
                  "https://sapientia.ro/hu/oktatas/tanarkepzes/rolunk",
                  "https://sapientia.ro/hu/oktatas/tanarkepzes/hasznos-informaciok",
                  "https://sapientia.ro/hu/oktatas/tanarkepzes/felveteli",
                  "https://sapientia.ro/hu/oktatas/tanarkepzes/a-pedagogiai-gyakorlat-megszervezese",
                  "https://sapientia.ro/hu/oktatas/tanarkepzes/a-zarovizsga-metodologiaja",
                  "https://sapientia.ro/hu/oktatas/tanarkepzes/tudomanyos-kutatasi-tevekenysegek",
                  "https://sapientia.ro/hu/oktatas/tanarkepzes/torvenyi-keretek",
                  "https://sapientia.ro/hu/oktatas/tanarkepzes/a-tanarkepzo-intezet-vezetosege-es-munkatarsai",
                  "https://sapientia.ro/hu/oktatas/tanarkepzes/mentortanaroknak-es-iranyitotanaroknak",
                  "https://sapientia.ro/hu/kutatas/kutatokozpontok/tanarkepzo-intezet"]

web_scraping_markdown_to_clean(tanarkepzes_urls)

append_md_file('markdown_hallgatoknak.md','markdown_bentlakas.md')

append_md_file('markdown_hallgatoknak.md','markdown_tanarkepzes.md')

append_md_file('markdown_hallgatoknak.md','markdown_zarovizsga.md')

kutatas_urls = ["https://ms.sapientia.ro/hu/kutatas",
                "https://ms.sapientia.ro/hu/kutatas/kutatokozpontok",
                "https://ms.sapientia.ro/hu/kutatas/kutatokozpontok/matinfo-matematika-es-informatika-kutatokozpont",
                "https://ms.sapientia.ro/hu/kutatas/kutatokozpontok/media-es-kommunikacio-kutatokozpont",
                "https://ms.sapientia.ro/hu/kutatas/kutatokozpontok/acfa-automatizalas-szamitastechnika-es-alkalmazott-fizika-kutatokozpont",
                "https://ms.sapientia.ro/hu/kutatas/kutatokozpontok/kerteszeti-biologiai-es-alkalmazott-kemiai-kutatokozpont",
                "https://ms.sapientia.ro/hu/kutatas/kutatokozpontok/ipari-mernok-es-alkalmazott-fizika-kutatokozpont",
                "https://ms.sapientia.ro/hu/kutatas/kutatokozpontok/damerg-nyelveszeti-kutatokozpont",
                "https://ms.sapientia.ro/hu/kutatas/kutatokozpontok/eletminoseg-kutatokozpont",
                "https://ms.sapientia.ro/hu/kutatas/kutatocsoportok/alkalmazott-nyelveszeti-tanszek_/damerg",
                "https://ms.sapientia.ro/hu/kutatas/kutatocsoportok/alkalmazott-tarsadalomtudomanyok-tanszek/uj-media-kutatocsoport",
                "https://ms.sapientia.ro/hu/kutatas/kutatocsoportok/alkalmazott-tarsadalomtudomanyok-tanszek/az-egeszsegi-allapot-es-az-eletminoseg-vizsgalata",
                "https://ms.sapientia.ro/hu/kutatas/kutatocsoportok/gepeszmernoki-tanszek_/alkalmazott-fizika-es-gepeszeti-tudomanyok-kutatokozpont",
                "https://ms.sapientia.ro/hu/kutatas/kutatocsoportok/kerteszmernoki-tanszek_/ppgroup",
                "https://ms.sapientia.ro/hu/kutatas/kutatocsoportok/matematika-informatika-tanszek_/biointelligencia-kutatocsoport",
                "https://ms.sapientia.ro/hu/kutatas/kutatocsoportok/matematika-informatika-tanszek_/cal-sapientia",
                "https://ms.sapientia.ro/hu/kutatas/kutatocsoportok/matematika-informatika-tanszek_/cirg",
                "https://ms.sapientia.ro/hu/kutatas/kutatocsoportok/matematika-informatika-tanszek_/research-group-in-mathematics",
                "https://ms.sapientia.ro/hu/kutatas/kutatocsoportok/villamosmernoki-tanszek_/apembsys",
                "https://ms.sapientia.ro/hu/kutatas/kutatocsoportok/villamosmernoki-tanszek_/cirg_",
                "https://ms.sapientia.ro/hu/kutatas/kutatocsoportok/villamosmernoki-tanszek_/narc",
                "https://ms.sapientia.ro/hu/kutatas/kutatocsoportok/villamosmernoki-tanszek_/pedimco",
                "https://ms.sapientia.ro/hu/kutatas/kutatocsoportok/villamosmernoki-tanszek_/prrg",
                "https://ms.sapientia.ro/hu/kutatas/palyazatok",
                "https://ms.sapientia.ro/hu/kutatas/palyazatok/palyazatok-oktatoknak/rendszeres-palyazatok/collegium-talentum-20242025",
                "https://ms.sapientia.ro/hu/kutatas/palyazatok/palyazatok-oktatoknak/rendszeres-palyazatok/horizont-europa-program",
                "https://ms.sapientia.ro/hu/kutatas/palyazatok/palyazatok-oktatoknak/rendszeres-palyazatok/kab-palyazatok",
                "https://ms.sapientia.ro/hu/kutatas/palyazatok/palyazatok-oktatoknak/rendszeres-palyazatok/sapientia-palyazatok/palyazat-kari-oktatoi-minositesi-potlek-megitelesere-a-2025-os-evre",
                "https://ms.sapientia.ro/hu/kutatas/palyazatok/palyazatok-oktatoknak/rendszeres-palyazatok/uefiscdi-palyazatok",
                "https://ms.sapientia.ro/hu/kutatas/palyazatok/palyazatok-oktatoknak/rendszeres-palyazatok/mta-palyazatok/domus-szulofoldi-osztondijpalyazat-2025",
                "https://ms.sapientia.ro/hu/kutatas/palyazatok/palyazatok-oktatoknak/rendszeres-palyazatok/mta-palyazatok/domus-magyarorszagi-osztondijpalyazat-2025-tavasz",
                "https://ms.sapientia.ro/hu/kutatas/palyazatok/palyazatok-oktatoknak/rendszeres-palyazatok/mta-palyazatok/domus-alkotoi-osztondijpalyazat-2025",
                "https://ms.sapientia.ro/hu/kutatas/palyazatok/palyazatok-oktatoknak/rendszeres-palyazatok/mta-palyazatok/palyazat-a-magyar-tudomanyos-akademia-bolyai-janos-kutatasi-osztondijanak-elnyeresere-2025-ben",
                "https://ms.sapientia.ro/hu/kutatas/palyazatok/palyazatok-oktatoknak/palyazatok_",
                "https://ms.sapientia.ro/hu/kutatas/szakkollegiumok",
                "https://ms.sapientia.ro/hu/kutatas/szakkollegiumok/kiss-elemer-szakkollegium/torteneti-ismerteto"]

web_scraping_markdown_to_clean(kutatas_urls)

nemzetkozi_kapcsolatok_urls=[
              "https://ms.sapientia.ro/hu/nemzetkozi-kapcsolatok",
              "https://ms.sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus",
              "https://sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/hallgatok/erasmus-hallgatoi-palyazati-felhivas-szakmai-gyakorlat-mobilitas-2025-nyara-es-tanulmanyi-mobilitas-202526-os-tanev",
              "https://sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/oktatok/erasmus-palyazati-felhivas-felsooktatasi-munkatarsak-kepzesi-celu-mobilitasara-stt-az-unios-tagallamokban-valamint-a-programhoz-tarsult-es-nem-tarsult-harmadik-orszagokban-a-2024-2025-os-tanevben-ka131",
              "https://sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/oktatok/erasmus-palyazati-felhivas-az-unios-tagallamokban-valamint-a-programhoz-tarsult-es-nem-tarsult-harmadik-orszagokban-megvalosulo-oktatasi-celu-mobilitasra-sta-a-2024-2025-os-tanevben-ka131",
              "https://sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/vegyes-intenziv-programok-bip/erasmus-mobilitas-palyazati-felhivas-oktatok-szamara-kozremukodokent-trainer-valo-reszvetelre-vegyes-intenziv-programokban-bip-a-2024-2025-os-tanevben",
              "https://sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/vendegek",
              "https://sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/vendegek/isten-hozott-az-egyetemunkre",
              "https://sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/vendegek/udvozlunk-erdelyben",
              "https://sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/vendegek/roviden-az-egyetemrol",
              "https://sapientia.ro/hu/az-egyetemrol/oktatasi-helyszinek",
              "https://sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/vendegek/targylistak",
              "https://sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/vendegek/jo-tudni",
              "https://sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/vendegek/jelentkezes",
              "https://sapientia.ro/hu/nemzetkozi-kapcsolatok/partnerintezmenyek",
              "https://sapientia.ro/hu/nemzetkozi-kapcsolatok/makovecz-program",
              "https://sapientia.ro/hu/nemzetkozi-kapcsolatok/nemzetkozi-hallgatoknak",
              "https://ms.sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/palyazati-felhivasok-hallgatok/bip-palyazati-felhivasok",
              "https://ms.sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/palyazati-felhivasok-hallgatok/bip-palyazati-felhivasok/meghivasos-erasmus-hallgatoi-mobilitas-palyazati-felhivas-rovid-vegyes-tanulmanyi-mobilitason-valo-reszvetel-vegyes-intenziv-program-bip-kereteben",
              "https://ms.sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/erasmus-kiutazo-diakok-beszamolok",
              "https://ms.sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/erasmus-kiutazo-diakok-beszamolok/rovid-szakmai-gyakorlatok",
              "https://ms.sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/bip-mobilitasok-2022-2023",
              "https://ms.sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/erasmus-partnerek",
              "https://ms.sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/erasmus-projektek",
              "https://sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/dokumentumok-szabalyzatok",
              "https://sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/erasmus-kapcsolat",
              "https://ms.sapientia.ro/hu/nemzetkozi-kapcsolatok/erasmus/hasznos-informaciok",
              ]

web_scraping_markdown_to_clean(nemzetkozi_kapcsolatok_urls)